### GET
GET http://localhost:3000/tasks


### POST
POST http://localhost:3000/tasks/new
Content-Type: application/json

{
  "title": "Test Task",
  "dueDate": "2026-03-20"
}

### PATCH
PATCH http://localhost:3000/tasks/complete/2


### PATCH
PATCH http://localhost:3000/tasks/incomplete/2


### DELETE
DELETE http://localhost:3000/tasks/delete/1


### PUT
PUT http://localhost:3000/tasks/edit/2
Content-Type: application/json

{
    "title": "Test Task (edited)",
    "dueDate": "2026-03-30"
}